### ISSUE TITLE
Upgrade doctrine ORM to use migration

### ISSUE THREAD

**Issue by bsmmoon** [codebendercc/eratosthenes#19]

**Comment by thngkaiyuan** [comment]
## Impetus:
The current version of Doctrine ORM in the project is 2.3. However, the developers would like to use Doctrine migrations which is only supported from Doctrine ORM 2.4 onwards. Therefore, an upgrade from Doctrine ORM 2.3 to 2.4 is required.

**Comment by thngkaiyuan** [comment]
It seems like we're not affected by any of the changes.
