### ISSUE TITLE
Implement new entities to support new tables

### ISSUE THREAD

**Issue by bsmmoon** [codebendercc/eratosthenes#21]
## Entities:
- [x] Preference (Issue #25)
- [x] Partner (Issue #26)
- [x] Architecture (Issue #27)
- [x] Library (Issue #30)
- [x] Version (Issue #29)
- [x] LibraryExample (Issue #31)

**Comment by bsmmoon** [comment]
**Default**
_id_, library_id, partner_id, version_id

**Partner**
_id_, name, auth_key

**Arch**
_id_, name

**External Lib**
_id_, human_name, machine_name, desc, notes, url

**Comment by bsmmoon** [comment]
@thngkaiyuan @Gisonrg Could you correct the table detail? Thanks!

**Comment by Gisonrg** [comment]
@thngkaiyuan @bsmmoon For ExternalLibrary and Example entity, shall we modify them directly or create new entity file first? Since these two are already there, if we directly modify them in their original file then may lead to some problems to the system?
