### ISSUE TITLE
Create CodeExample Entity

### ISSUE THREAD

**Issue by bsmmoon** [codebendercc/eratosthenes#31]
id, version_id, name, path, boards
Unique index on: version_id

Renamed from Example to CodeExample.

**Comment by Gisonrg** [comment]
We have a problem here if version_id is unique:
**what if there are more than 1 examples for the same version?**
I met this issue when I was populating fixtures.

**Comment by bsmmoon** [comment]
What about we make (version_id, name) combination as a unique constraint?

**Comment by bsmmoon** [comment]
OK since this issue is addressed in #36 as well, let's discuss over there.
