### ISSUE TITLE
Modify file organisation for the new structure

### ISSUE THREAD

**Issue by bsmmoon** [codebendercc/eratosthenes#32]
To do:
- Modify LoadExternalLibraryFilesCommand.php
- Modify DefaultHandler.php

These are passed to later issues. This issue will focus on new file structure.

**Comment by bsmmoon** [comment]
Structure:
Library
    Version
        .(files)
         Example

Architecture?

**Comment by bsmmoon** [comment]
@spiliot

**Comment by bsmmoon** [comment]
- get the version of the library
- escape invalid characters (how?)

**Comment by Gisonrg** [comment]
Looks OK

**Comment by thngkaiyuan** [comment]
@bsmmoon:
Shouldn't the structure look like this:
```
|-- library_name
|    |-- version_name
|    |    |-- (files)
|    |    |-- (example)
```

Also, I suspect that you might need to also modify other files (aside from LoadExternalLibraryFilesCommand.php)

I think if we have more than one variation of a library version (e.g. DefaultLibrary v1.1 that supports AVR and a different DefaultLibrary v1.1 that support ARM) we can simply use the same name conflict resolution mechanism that we use to resolve same escaped version names to resolve this issue. For example, if the relative path `Default/1.1` already exists, we use the name conflict resolution mechanism to create a different folder name, say `Default/1.1_1`.

**Comment by Gisonrg** [comment]
@bsmmoon 
You may need to add some helper functions in Entity or Handler
For example, create a helper function to escape the special characters in DefaulterHandler for library creating
A path generating function to generate the path to a version may also be helpful.

@thngkaiyuan 
Actually I think most of the cases there can only be multiple architecture supported under the same version number. But your suggestion is good, we should also check if there is any conflict version number when add new library version.

I think after we finish database stuffs we can start to work on the view for adding new library. At that time we will know how many helpful function we really need

**Comment by bsmmoon** [comment]
branched out from create-new-entities to modify-organisation

**Comment by bsmmoon** [comment]
Change in LoadExternalLibraryFilesCommand may actually be not necessary as it simply delete the whole directory and mirror \LibraryBundle\Resources\library_files with exactly the same structure.

**Comment by bsmmoon** [comment]
Refer to the branch **change-library-structure **
https://github.com/codebendercc/eratosthenes/tree/change-library-structure

**Comment by spiliot** [comment]
@bsmmoon Adding mentions like you do here https://github.com/codebendercc/eratosthenes/issues/32#issuecomment-178584514 isn't helpful. If you want to bring something to someone's attention do it with a direct question!

**Comment by spiliot** [comment]
@Gisonrg Closing an issue should be followed by a comment (why it closes). An issue can close perhaps because it is invalid or decided as not fixable, superseded by a new one (mention the new one), because a fix is provided in a PR (mention the PR). Reading this now, I'm not sure what was the reason to close this and the direct previous comment mentions a branch, not a PR.

**Comment by Gisonrg** [comment]
@spiliot Notice, I will pay attention next time.
